from typing import Any

# Stubs for flame
class PyActionFamilyNode: ...
class PyActionNode: ...
class PyArchiveEntry: ...
class PyAttribute: ...
class PyAudioTrack: ...
class PyBatch: ...
class PyBatchIteration: ...
class PyBrowser: ...
class PyClip: ...
class PyClipNode: ...
class PyClrMgmtNode: ...
class PyCoCameraAnalysis: ...
class PyCoCompass: ...
class PyCoNode: ...
class PyColourMgtTimelineFX: ...
class PyCompassNode: ...
class PyDesktop: ...
class PyExporter: ...
class PyFlameObject: ...
class PyFolder: ...
class PyGMaskTracerNode: ...
class PyHDRNode: ...
class PyHDRTimelineFX: ...
class PyImageNode: ...
class PyLensDistortionNode: ...
class PyLibrary: ...
class PyMarker: ...
class PyMediaHub: ...
class PyMediaHubFilesEntry: ...
class PyMediaHubFilesFolder: ...
class PyMediaHubFilesTab: ...
class PyMediaHubFilesTabOptions: ...
class PyMediaHubProjectsEntry: ...
class PyMediaHubProjectsFolder: ...
class PyMediaHubTab: ...
class PyMediaPanel: ...
class PyMessages: ...
class PyMetadataNode: ...
class PyMetadataTimelineFX: ...
class PyMetadataValue: ...
class PyMorphNode: ...
class PyNode: ...
class PyOFXNode: ...
class PyPaintNode: ...
class PyProject: ...
class PyProjectSelector: ...
class PyReadFileNode: ...
class PyReel: ...
class PyReelGroup: ...
class PyRenderNode: ...
class PyResolution: ...
class PySearch: ...
class PySegment: ...
class PySequence: ...
class PySequenceGroup: ...
class PySubtitleTrack: ...
class PyTime: ...
class PyTimeline: ...
class PyTimelineFX: ...
class PyTimewarpNode: ...
class PyTimewarpTimelineFX: ...
class PyTrack: ...
class PyTransition: ...
class PyTypeFX: ...
class PyTypeLayer: ...
class PyTypeNode: ...
class PyUser: ...
class PyUsers: ...
class PyVersion: ...
class PyWorkspace: ...
class PyWriteFileNode: ...
batch: Any
browser: Any
clear_graphics_memory: Any
clear_unreferenced_cache: Any
delete: Any
duplicate: Any
duplicate_many: Any
execute_command: Any
execute_shortcut: Any
exit: Any
find_by_name: Any
find_by_uid: Any
find_by_wiretap_node_id: Any
flush_graphics_memory: Any
get_current_tab: Any
get_home_directory: Any
get_init_cfg_path: Any
get_version: Any
get_version_major: Any
get_version_minor: Any
get_version_patch: Any
get_version_stamp: Any
go_to: Any
import_clips: Any
media_panel: Any
mediahub: Any
messages: Any
project: Any
projects: Any
schedule_idle_event: Any
set_current_tab: Any
set_render_option: Any
timeline: Any
users: Any
